Flags on family page (recently donated) windows
Duet-USC/duet pull request #87
Opened 2020-09-17 00:55 UTC by washingtonzhao

- Downloaded pngs of all currently supported country flags (in flags.js) locally to public/static/flags (included hong kong as well since saw on site hong kong donation)

- Display img with appropriate flag png src link in components/FamilyProfile/ItemCard.jsx based on lastDonor.donorCountry -- png adjusted for height of text 

**Next steps:

- Implement react context to check for user on windows or non-windows to use emojis (previous implementation) on non-windows and pngs only on windows

**

2020-09-17 05:14 UTC, lucashu1 commented
Converting to draft as you work on hosting the flags on the CDN @washingtonzhao, tag @Raghav-Maheshwari and me as reviewers once that's been updated!

2020-09-18 04:40 UTC, lucashu1 commented
@washingtonzhao Looks like you got the CDN working properly! The flags show up properly in the Recently Donated section.

A few more tweaks while we're at it:

**1.** Can you fix the flags on the family banner as well? E.g. where it says "Afghanistan -> Greece".
<img width="1157" alt="Screen Shot 2020-09-17 at 9 31 59 PM" src="https://user-images.githubusercontent.com/1973414/93556422-8d701980-f92d-11ea-8fb7-171058879ac9.png">

**2.** The flags unfortunately do take a bit longer to load than the emojis, so it might be worthwhile to pre-shrink the flag images before uploading them to the CDN. Perhaps to a size that's just larger than is necessary to fit the slightly larger text inside the family banner.

**3.** With the PNG version, the flags don't appear as neatly centered as they did with the emoji version.

You may consider playing around with the CSS a bit to see if you can get the PNG version to match as closely as possible with the emoji version in terms of positioning. (Every pixel counts!)

**PNG version:**
<img width="157" alt="Screen Shot 2020-09-17 at 9 37 43 PM" src="https://user-images.githubusercontent.com/1973414/93556681-269f3000-f92e-11ea-9314-b5f3e38d28e0.png">

**Emoji version:**
<img width="158" alt="Screen Shot 2020-09-17 at 9 37 34 PM" src="https://user-images.githubusercontent.com/1973414/93556672-230ba900-f92e-11ea-9098-457c50f3fb1b.png">

2020-09-21 02:18 UTC, washingtonzhao commented
@lucashu1  @Raghav-Maheshwari 

Made 3 changes listed in Lucas' comment-- awaiting review

2020-09-22 02:54 UTC, lucashu1 commented
@washingtonzhao Flags aren't showing up for me anymore (see screenshot). One reason might be that you forgot to give "public read" permissions to the PNGs when uploading them to S3. E.g. opening https://cdn.giveduet.org/website-images/Afghanistan.png show an "Access Denied" message.

Also, I noticed that you sometimes put `verticalAlign: 'bottom'` and sometimes `verticalAlign: 'top'` for the `img` positioning. Is there a particular reason for that difference? (Just curious -- there very well might be a reason, but I'm unable to see the flags right now)

<img width="1186" alt="Screen Shot 2020-09-21 at 7 49 33 PM" src="https://user-images.githubusercontent.com/1973414/93839978-96216200-fc43-11ea-91fc-44eab3387017.png">

2020-09-22 03:02 UTC, lucashu1 requested changes
@washingtonzhao Flags aren't showing up for me anymore (see screenshot). One reason might be that you forgot to give "public read" permissions to the PNGs when uploading them to S3. E.g. opening https://cdn.giveduet.org/website-images/Afghanistan.png show an "Access Denied" message.

Also, I noticed that you sometimes put `verticalAlign: 'bottom'` and sometimes `verticalAlign: 'top'` for the `img` positioning. Is there a particular reason for that difference? (Just curious -- there very well might be a reason, but I'm unable to see the flags right now)

<img width="1186" alt="Screen Shot 2020-09-21 at 7 49 33 PM" src="https://user-images.githubusercontent.com/1973414/93839978-96216200-fc43-11ea-91fc-44eab3387017.png">

2020-09-22 05:30 UTC, Raghav-Maheshwari approved these changes
left some nits, but looks good to me!

Also, if your PR changes the frontend in any way, please add screenshots of those changes as part of the PR description

2020-09-22 05:30 UTC, Raghav-Maheshwari commented on packages/frontend/components/FamilyProfile/ItemCard.jsx
> +// import { flags } from '../../constants';
nit: let's remove this import (instead of commenting it out) if it's not needed anymore.

2020-09-22 05:30 UTC, Raghav-Maheshwari commented on packages/frontend/components/FamilyProfile/ItemCard.jsx
> +      verticalAlign: 'bottom',
vertical-align only works with inline, inline-block, or table-cell elements right?
If you want to use `verticalAlign` you might need to set the display property accordingly. 

Another way (I think) you could do this is making `donatedBy` a flexbox and doing `alignItems: 'center'`

2020-09-22 05:30 UTC, Raghav-Maheshwari commented on packages/frontend/components/FamilyProfile/ItemCard.jsx
> +        Donated by {lastDonor.donorFirst}{' '}
nit: the linter might have added the `{' '}` but see if you can replace it with `&nbsp;` instead (cleaner imo)

2020-09-22 05:30 UTC, Raghav-Maheshwari commented on packages/frontend/components/FamilyProfile/Journey.jsx
> +        {` `} → {` ${familyInfo.currentCity}, ${familyInfo.currentCountry} `}
same as above

2020-09-22 10:03 UTC, washingtonzhao commented on packages/frontend/components/FamilyProfile/ItemCard.jsx
> +      verticalAlign: 'bottom',
using it on an img element which is treated essentially treated like an inline-block so to my knowledge it should work as expected/ just based-on at a glance view vertical-align is changing the image position as well

2020-09-22 10:06 UTC, washingtonzhao commented
![PR1](https://user-images.githubusercontent.com/42752230/93869132-457c2a00-fc80-11ea-88c0-82eee1bf95ad.PNG)
![PR2](https://user-images.githubusercontent.com/42752230/93869136-4614c080-fc80-11ea-8abd-3e23d184f4d8.PNG)
![PR3](https://user-images.githubusercontent.com/42752230/93869212-5d53ae00-fc80-11ea-8436-c6116a49ea1d.PNG)
(all on windows)

@lucashu1 @Raghav-Maheshwari 
- uniformed all vertical aligned images to be bottom aligned
- gave public read permissions (sorry about that, should be good now to view)
- changed formatting of spaces to &nbsp;

2020-09-23 03:21 UTC, lucashu1 commented
@washingtonzhao Looking great! I think the last thing is just to fix the flag positioning in the "Meet Another Family" section, but after that, I think this is good to go!

<img width="1195" alt="Screen Shot 2020-09-22 at 8 20 38 PM" src="https://user-images.githubusercontent.com/1973414/93963088-16fa5f80-fd11-11ea-9253-c3a8b9e1c831.png">

2020-09-23 11:33 UTC, washingtonzhao commented
![PR5](https://user-images.githubusercontent.com/42752230/94006483-c3aa0080-fd54-11ea-8c7f-cef8a7dca50e.PNG)
![PR6](https://user-images.githubusercontent.com/42752230/94006488-c4429700-fd54-11ea-9e19-4bcd8de7d823.PNG)

Updated the vertical align for flag element in MeetAnotherFamily.jsx back to 'top' compared to 'bottom' for all the other flags-- not completely sure why but think it has to do the with the difference in vertical text alignment, so based the decisions on a visual glance on how the flags looked

2020-09-23 23:20 UTC, lucashu1 approved these changes

2020-09-23 23:21 UTC, lucashu1 commented
Awesome -- merging this in now @washingtonzhao. Congrats on your first Duet PR :)

2020-09-23 23:21 UTC, merged