Add 404 not found page
Duet-USC/duet pull request #92
Opened 2020-09-21 23:03 UTC by zero-delta

### Description

- Add 404 not found page 
- Available at `/pages/404`

### Screenshots
![notfoundpage](https://user-images.githubusercontent.com/54155282/93830005-01b40100-fc3d-11ea-8cff-1e593722186a.png)

2020-09-22 01:09 UTC, zero-delta commented
Replacing NextJs Error component with custom 404 NotFound component in `[...slug].jsx` 
Now uses the custom NotFound page for all 404 status codes.

2020-09-22 03:01 UTC, lucashu1 commented
@zero-delta The main 404 functionality is working for me! However, the error message looks pretty weird when rendered on Safari (see screenshot). I think it might be due to the usage of `<h1>`. Instead of `<h1>`, maybe just try using a regular `div` with CSS styling for the text instead?

Nit: if the rest of the text is bold, we might wanna make the "here" link bold as well.

**Safari:**
<img width="1440" alt="Screen Shot 2020-09-21 at 7 54 57 PM" src="https://user-images.githubusercontent.com/1973414/93840226-8f471f00-fc44-11ea-829d-358ea2a2ed6c.png">

**Inspect Element:**
<img width="1440" alt="Screen Shot 2020-09-21 at 7 57 56 PM" src="https://user-images.githubusercontent.com/1973414/93840289-c1f11780-fc44-11ea-8100-1a9c169db5ee.png">

2020-09-22 03:02 UTC, lucashu1 requested changes
@zero-delta The main 404 functionality is working for me! However, the error message looks pretty weird when rendered on Safari (see screenshot). I think it might be due to the usage of `<h1>`. Instead of `<h1>`, maybe just try using a regular `div` with CSS styling for the text instead?

Nit: if the rest of the text is bold, we might wanna make the "here" link bold as well.

**Safari:**
<img width="1440" alt="Screen Shot 2020-09-21 at 7 54 57 PM" src="https://user-images.githubusercontent.com/1973414/93840226-8f471f00-fc44-11ea-829d-358ea2a2ed6c.png">

**Inspect Element:**
<img width="1440" alt="Screen Shot 2020-09-21 at 7 57 56 PM" src="https://user-images.githubusercontent.com/1973414/93840289-c1f11780-fc44-11ea-8100-1a9c169db5ee.png">

2020-09-22 05:24 UTC, Raghav-Maheshwari approved these changes
left a couple of nits - once you address Lucas's comments, it looks good to me!

2020-09-22 05:24 UTC, Raghav-Maheshwari commented on packages/frontend/pages/404.jsx
> +    justifyContent: 'center',
nit: not sure if you actually need to use flexbox here - you should be able to achieve what you want with `textAlign: 'center'`

2020-09-22 05:24 UTC, Raghav-Maheshwari commented on packages/frontend/pages/404.jsx
> +            {' '}
the linter might have added the `{' '}`, but could we try removing them? If not, you can use `&nbsp;` as a space

2020-09-23 22:28 UTC, zero-delta commented on packages/frontend/pages/404.jsx
> +    justifyContent: 'center',
When I try `textAlign: 'center'` : 
![image](https://user-images.githubusercontent.com/54155282/94074943-3dc79d00-fdc8-11ea-96d5-1a444b915c2b.png)
it ends up moving it to the top:
![noflex](https://user-images.githubusercontent.com/54155282/94074912-2d172700-fdc8-11ea-9086-48c9b8f6776f.png)

I tried adding paddingTop and some other stuff, but the text ends up going to the next line.
![image](https://user-images.githubusercontent.com/54155282/94076227-9d26ac80-fdca-11ea-8364-eb2c2133304f.png)
![image](https://user-images.githubusercontent.com/54155282/94076201-8f712700-fdca-11ea-9f5c-8505285bc668.png)

2020-09-23 22:33 UTC, zero-delta commented
Replaced `<h1>` with `<div>` and some font formatting
Safari:
![safari7](https://user-images.githubusercontent.com/54155282/94076495-3ce43a80-fdcb-11ea-83b6-e43ceafc9b76.png)
Chrome:
![chrome](https://user-images.githubusercontent.com/54155282/94076496-3ce43a80-fdcb-11ea-8cc2-96f3bd6725fc.png)

2020-09-23 23:50 UTC, lucashu1 commented
@zero-delta I was still getting the weird separated-text error when I shrunk my screen size so that the text didn't fit onto a single line.

<img width="797" alt="Screen Shot 2020-09-23 at 4 49 09 PM" src="https://user-images.githubusercontent.com/1973414/94085353-b6286100-fdbc-11ea-9504-14a7ca26e804.png">

In order to fix this, I made some tweaks to the HTML/CSS. The main changes to fix that bug were:
* Put all text in a single `div` so that `flex-wrap` doesn't separate `divs` when text doesn't fit onto a single line
* Remove `flexWrap`
* Add `textAlign: center`
* Added `flexDirection: column` (although idk if this really did anything)

Additionally: 
* Added `marginTop: 80` (to leave room for absolutely positioned NavBar)
* Add padding to the left and right sides of the container (20px)

Be sure to take a look at the updated code and make sure you know what each of these properties are doing! Wanted to free up your queue before we create more assignments for this upcoming sprint.

In order to catch visual bugs like this, we'll typically use "Inspect Element" to inspect the page on a variety of screen sizes, since a lot of our donors visit the site on mobile as well. So we need to make sure that things work on a variety of screen sizes.

2020-09-23 23:53 UTC, lucashu1 approved these changes

2020-09-23 23:53 UTC, merged